name: Android Compile and produce

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:        
      - v*

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 13 ]

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    needs: test
    name: Generate APK
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 13 ]

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build debug APK
        run: |
          bash ./gradlew assembleDebug --stacktrace
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/CovidManager.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/debug/CovidManager.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}